title: BG Tools
description: "Free Online Tools - YouTube, Image, Video, PDF, Text, Calculator aur Resume Tools. 100% Free, No Signup."
url: "https://bgsarkariresult.github.io"
baseurl: "/BG-Tools-All-IN-ONE"
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
lang: hi
author: BG Tools
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
include:
  - .well-known
